### ISSUE TITLE
Feedback: Proposal

### ISSUE THREAD

**Issue by s-pangburn** [Tianyou-Song/MusicMist#1]
Hi Tim! Great work! 

## MVP List
- No feedback! Well done! :)

## Schema
- [ ] Include your `belongs_to` and `has_many` associations! Also refer to [Bluebird](https://github.com/appacademy/bluebird/wiki/schema) for additional information you should include.

## Sample State
- [ ] Don't include session token and password digest in your frontend state! It's sensitive information and you won't be using it for anything anyway.
- [ ] You probably also don't need `created_at` or `updated_at`. `created_at` could be useful in some cases, but you should be using JBuilder to only include the relevant data.
- [ ] If you're using a `contributions` join table, you should have arrays of ids for `contributedSongs` in the artists slice of state and `contributors` in the songs slice of state
- [ ] `comments` not `commentss`

## Frontend Routes
- [ ] Every component and route should be surrounded by `backticks`. Example:
  + `/users/:userId`
       + `ProfileComponent`
       + `UploadIndex`
           + `UploadIndexItem`

Everything else looks good! Let me know if you have any questions.

**Comment by Tianyou-Song** [comment]
I have updated the proposal accordingly.
However, I'm not sure how to write the `belogns_to` and `has_many` associations, since the bluebird example schema does not have them, so I just wrote out the raw activerecord associations, with ruby highlighting.
Please [take a look](https://github.com/Tianyou-Song/MusicMist/wiki/schema).

**Comment by s-pangburn** [comment]
Hey Tim! 

Sorry for the delay in your feedback. This looks good! Feel free to get started on your project if you haven't already 🙂
